# Generated by Django 3.2.2 on 2021-05-18 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='TITLE')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbti', models.CharField(choices=[('INTJ', '용의주도한 전략가'), ('INTP', '논리적인 사색가'), ('ENTJ', '대담한 통솔자'), ('ENTP', '뜨거운 논쟁을 즐기는 변론가'), ('INFJ', '선의의 옹호자'), ('INFP', '열정적인 중재자'), ('ENFJ', '정의로운 사회운동가'), ('ENFP', '재기발랄한 활동가'), ('ISTJ', '청렴결백한 논리주의자'), ('ISFJ', '용감한 수호자'), ('ESTJ', '엄격한 관리자'), ('ESFJ', '사교적인 외교관'), ('ISTP', '만능 재주꾼'), ('ISFP', '호기심 많은 예술가'), ('ESTP', '모험을 즐기는 사업가'), ('ESFP', '자유로운 영혼의 연예인')], max_length=4)),
                ('image', models.ImageField(null=True, upload_to='SorlPhoto/%Y', verbose_name='IMAGE')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='SLUG')),
                ('text', models.TextField(blank=True)),
                ('details', models.ManyToManyField(to='question.DetailText')),
            ],
        ),
        migrations.CreateModel(
            name='Select',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=128)),
                ('indicator', models.CharField(choices=[('E', 'Extraversion'), ('I', 'Introversion'), ('S', 'Sensing'), ('N', 'iNtuition'), ('T', 'Thinking'), ('F', 'Feeling'), ('J', 'Judging'), ('P', 'Perceiving')], max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
            ],
        ),
    ]
