# Generated by Django 3.2.2 on 2021-05-22 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeindicator',
            name='hate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hate_mbti', to='question.typeindicator'),
        ),
        migrations.AddField(
            model_name='typeindicator',
            name='like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_mbti', to='question.typeindicator'),
        ),
    ]
